apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-ns-gateway
  namespace: default
  labels:
    traefik-gateway: traefik-2
spec:
  gatewayClassName: traefik-2
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: defaut-ns-gateway
    port: 8333
    protocol: HTTP
