apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  creationTimestamp: "2025-11-07T09:06:51Z"
  name: default-ipv4-ippool
  resourceVersion: "2286"
  uid: dfeb611d-03f1-4e83-b9fc-ea60cbc5a743
spec:
  allowedUses:
  - Workload
  - Tunnel
  assignmentMode: Automatic
  blockSize: 26
  cidr: 10.222.64.0/18
  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
