apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: pods-pool
spec:
  cidr: 10.244.64.0/18
  ipipMode: Never
  natOutgoing: true
  disabled: false
  nodeSelector: all()
  disabled: true
