---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: master-pool
spec:
  cidr: 115.115.0.0/18
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: node == "master"
  allowedUses:
    - Workload
    - Tunnel
  assignmentMode: Automatic
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: worker-nodes-pool
spec:
  cidr: 10.100.0.0/18
  ipipMode: Always
  natOutgoing: true
  disabled: false
  nodeSelector: node == "worker"
  allowedUses:
    - Workload
    - Tunnel
  assignmentMode: Automatic
