apiVersion: v1
kind: ConfigMap
metadata:
    name: kubernetes-services-endpoint
    namespace: tigera-operator
data:
    KUBERNETES_SERVICE_HOST: "192.168.0.100"  # Замените на ваш IP или FQDN API-сервера
    KUBERNETES_SERVICE_PORT: "7443"
