---
- name: Restart haproxy
  service:
    name: haproxy
    daemon_reload: true
    enabled: true
    state: started

- name: Restart keepalived
  service:
    name: keepalived
    daemon_reload: true
    enabled: true
    state: restarted
