---
- import_playbook: drop_k8s_cluster.yml
- import_playbook: install_ha.yml
- import_playbook: init_first_node.yml
- import_playbook: append_master_node.yml
- import_playbook: append_worker_node.yml
