apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  generation: 1
  name: whisker
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Whisker
    name: default
  resourceVersion: "252418"
spec:
  ingress:
  - ports:
    - port: 8081
      protocol: TCP
    from:
    - namespaceSelector:
       matchLabels:
         kubernetes.io/metadata.name: traefik
    - podSelector:
       matchLabels:
         app.kubernetes.io/name: traefik
  egress:
  - ports:
    - port: 7443
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: goldmane
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          projectcalico.org/name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  podSelector:
    matchLabels:
      app.kubernetes.io/name: whisker
  policyTypes:
  - Ingress
  - Egress
