apiVersion: v1
kind: Service
metadata:
    name: whisker-test
    namespace: calico-system   # ← НЕ calico-system!
spec:
    type: ClusterIP
    selector:
        k8s-app: whisker
    ports:
      - port: 8081
        targetPort: 8081  # можно указать, или пусть сам выберет
        protocol: TCP
