---
- name: Append master node
  shell: >
      kubeadm join {{ hostvars[item]['cluster_ip']  }} --token {{ hostvars[item]['ca_token'] }}  --discovery-token-ca-cert-hash sha256:{{ hostvars[item]['ca_fingerprint'] }}
      --certificate-key {{ hostvars[item]['ca_key'] }} --control-plane
  with_items: '{{ groups["init_node"] }}'

  


